/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javahis.reporting;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ustadho
 */
public class FrmReportInternalFrame extends javax.swing.JInternalFrame {
    private Connection conn;
    List lstUnit=new ArrayList();
    /**
     * Creates new form FrmReportInternalFrame
     */
    public FrmReportInternalFrame() {
        initComponents();
    }

    private void udfPreview(String sReport){
        try{
            HashMap reportParam = new HashMap();
            JasperReport jasperReport=null;
            String sSubRpt="", sGambar="";
//            sGambar=getClass().getResource("/resources/siloam_bw.jpg").toString();
//            sSubRpt=getClass().getResource("Reports/").toString();
            reportParam.put("sHospital", MainForm.sHospital);
            reportParam.put("sAddress", "Jl. POM ...");
            reportParam.put("sTelp", "012312312");
            reportParam.put("sKota", "Palembang");
            reportParam.put("tanggal1", new SimpleDateFormat("yyyy-MM-dd").format(jXDatePickerAwal.getDate()));
            reportParam.put("tanggal2", new SimpleDateFormat("yyyy-MM-dd").format(jXDatePickerAkhir.getDate()));
            reportParam.put("unit", lstUnit.get(cmbUnit.getSelectedIndex()).toString());
            
//            reportParam.put("sGambar", sGambar);
//            reportParam.put("SUBREPORT_DIR", sSubRpt);
            //reportParam.put("SUBREPORT_DIR", getClass().getResourceAsStream("Reports"));
            
            sReport="Reports/"+sReport+".jasper";
            //System.out.println("SUBREPORT_DIR "+ sSubRpt );
            System.out.println("sReport= "+ sReport );
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream(sReport));                                                
            JasperPrint print = JasperFillManager.fillReport(jasperReport,reportParam,conn);
            
            if(print.getPages().isEmpty()){
                JOptionPane.showMessageDialog(this, "Report tidak ditemukan!");
                return;
            }
            //print.setOrientation(Orientation.PORTRAIT);
            JasperViewer.viewReport(print,false);

        } 
        catch(JRException je){
            System.out.println(je.getMessage());
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePickerAkhir = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerAwal = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbUnit = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("report");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jXDatePickerAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));
        getContentPane().add(jXDatePickerAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel1.setText("Unit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 20));

        jLabel2.setText("Nama Report :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        jLabel3.setText("Tanggal Akhir :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        jLabel4.setText("Tanggal Akhir :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, -1));

        jButton1.setText("Preview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 70, -1));

        jLabel5.setText("Tanggal Awal :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1. Report Rekap Dokter", "2. Rekap .....", "3...." }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            cmbUnit.removeAllItems();
            ResultSet rs=conn.createStatement().executeQuery("select kode_unit, unit from rm_unit order by 2");
            while(rs.next()){
                lstUnit.add(rs.getString("kode_unit"));
                cmbUnit.addItem(rs.getString("unit"));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(jComboBox1.getSelectedIndex()){
            case 0:{
                udfPreview("Dokter");
            }
            default :{
                break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAkhir;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAwal;
    // End of variables declaration//GEN-END:variables

    void setConn(Connection con) {
        this.conn=con;
    }
}
